version: '3.7'
services:
#  zookeeper:
#    image: zookeeper:3.6.0
#    restart: on-failure
#
#  kafka:
#    image: wurstmeister/kafka:2.12-2.4.1
#    ports:
#      - "19101:9094"
#    environment:
#      KAFKA_BROKER_ID: 101
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:19101
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
#      KAFKA_CREATE_TOPICS: "TopicA:4:1,TopicB:4:1:compact"
#    depends_on:
#      - zookeeper
#    restart: on-failure

  seed0:
    hostname: seed0
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    environment:
      KAFKA_BROKER: kafka

  seed1:
    hostname: seed0
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    environment:
      KAFKA_BROKER: kafka

  seed2:
    hostname: seed0
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    environment:
      KAFKA_BROKER: kafka
